(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/notification/demo"],{

/***/ "./node_modules/bisheng/tmp/components-notification-demo.index.js":
/*!************************************************************************!*\
  !*** ./node_modules/bisheng/tmp/components-notification-demo.index.js ***!
  \************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports = {\n    'basic': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/basic.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/basic.md\"),\n    'custom-icon': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/custom-icon.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/custom-icon.md\"),\n    'custom-style': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/custom-style.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/custom-style.md\"),\n    'duration': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/duration.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/duration.md\"),\n    'hooks': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/hooks.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/hooks.md\"),\n    'placement': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/placement.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/placement.md\"),\n    'update': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/update.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/update.md\"),\n    'with-btn': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/with-btn.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/with-btn.md\"),\n    'with-icon': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/notification/demo/with-icon.md */ \"/Users/afc163/Projects/ant-design/node_modules/bisheng/lib/loaders/source-loader!/Users/afc163/Projects/ant-design/components/notification/demo/with-icon.md\"),\n}\n\n//# sourceURL=webpack:///./node_modules/bisheng/tmp/components-notification-demo.index.js?");

/***/ })

}]);